- name: app steup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: app steup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs  

- name: app steup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd


