- name: Install Python pacakages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
    loop:
    - python36
    - gcc
    - python3-devel

- name: install dependicies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app